<?php
declare(strict_types=1);
require __DIR__.'/ebooks-lib.php';
k9_headers();
if(($_SERVER['REQUEST_METHOD']??'')!=='GET')k9_error(405,'Please return to the K9 Academy website.');
try{
    if(!k9_rate_limit('confirmation',40))k9_error(429,'Please try again later.');
    $id=$_GET['session_id']??'';if(!is_string($id))throw new RuntimeException('invalid_session');
    $order=k9_fulfill($id);$config=k9_config();$links=k9_links($order);$bg=$order['language']==='bg';$e=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
    header('Content-Type: text/html; charset=utf-8');
    echo '<!doctype html><html lang="'.($bg?'bg':'en').'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.($bg?'Вашите ръководства':'Your guides').' | K9 Academy</title><style>body{margin:0;background:#f4f2e9;color:#172011;font:18px/1.65 system-ui}main{max-width:720px;padding:40px 24px;margin:5vh auto}h1{font-size:clamp(2rem,6vw,3.7rem);line-height:1.1}a{color:#253e12}.download{display:block;padding:18px 24px;background:#d9ff00;color:#172011;border-radius:15px;margin:16px 0;text-decoration:none;font-weight:bold}small{display:block;color:#58634f}</style></head><body><main><p>K9 ACADEMY / PDF</p><h1>'.($bg?'Благодарим за покупката.':'Thank you for your purchase.').'</h1><p>'.$e($config['products'][$order['product']]['name'][$order['language']]).'</p><a class="download" href="'.$e($links['bg']).'">'.($bg?'Изтегли PDF на български':'Download the Bulgarian PDF').'</a><a class="download" href="'.$e($links['en']).'">'.($bg?'Изтегли PDF на английски':'Download the English PDF').'</a><p>'.($order['mail']==='accepted'?($bg?'Изпратихме двата файла и на имейла от покупката. Проверете и папката за нежелана поща.':'Both files have also been sent to your checkout email. Please check your spam folder too.'):($bg?'Файловете са готови за изтегляне. Доставката по имейл изисква проверка; свържете се с нас, ако не получите съобщението.':'The files are ready to download. Email delivery needs review; contact us if the message does not arrive.')).'</p><small>'.($bg?'Линковете са валидни 30 дни. Запазете файловете за лично ползване.':'The links are valid for 30 days. Keep the files for personal use.').'</small><p><a href="mailto:mail.k9shop@gmail.com">mail.k9shop@gmail.com</a></p><a href="'.K9_ORIGIN.'/'.($bg?'':'en/').'ebooks/">'.($bg?'Към K9 Academy':'Return to K9 Academy').'</a></main></body></html>';
}catch(Throwable $error){k9_error(403,'Your payment has not been confirmed. If you paid, please contact K9 Academy.');}
