<?php
require __DIR__ . '/site.php';
require __DIR__ . '/head.php';
require __DIR__ . '/header.php';
$post = $article[$lang];
?>
<main id="main-content"><article>
<section class="editorial-hero k9-textured"><div class="site-container article-heading"><nav class="article-breadcrumb" aria-label="<?= $lang==='bg'?'Път до страницата':'Breadcrumb' ?>"><a href="<?= k9e(k9_url('index.php')) ?>"><?= k9e(k9t('nav_home')) ?></a><span>/</span><a href="<?= k9e(k9_url('blog.php')) ?>"><?= k9e(k9t('nav_blog')) ?></a></nav><p class="eyebrow"><?= k9e($post['category']) ?> / K9 ACADEMY</p><h1><?= k9e($post['title']) ?></h1><p class="editorial-lead"><?= k9e($post['intro']) ?></p><p class="article-date"><?= $lang==='bg'?'Публикувано на 9 октомври 2026 г. · Практическо ръководство':'Published 9 October 2026 · Practical guide' ?></p></div></section>
<section class="editorial-reading k9-textured"><div class="site-container reading-layout"><nav class="reading-index" aria-label="<?= $lang==='bg'?'Съдържание':'Contents' ?>"><?php foreach ($post['sections'] as $i=>$section): ?><a href="#article-<?= $i ?>"><?= k9e($section['title']) ?></a><?php endforeach; ?></nav><div class="reading-copy">
<figure class="article-photo"><img src="/assets/images/training-library/training-<?= str_pad((string)$article['photo'],3,'0',STR_PAD_LEFT) ?>-1280.webp" srcset="/assets/images/training-library/training-<?= str_pad((string)$article['photo'],3,'0',STR_PAD_LEFT) ?>-640.webp 640w, /assets/images/training-library/training-<?= str_pad((string)$article['photo'],3,'0',STR_PAD_LEFT) ?>-1280.webp 1280w" sizes="(min-width: 900px) 65vw, 100vw" width="1280" height="853" alt="<?= k9e($post['imageAlt']) ?>" loading="lazy" decoding="async"></figure>
<?php foreach ($post['sections'] as $i=>$section): ?><section id="article-<?= $i ?>"><h2><?= k9e($section['title']) ?></h2><?= k9_editorial_html($section['body']) ?></section><?php endforeach; ?>
<aside class="editorial-callout"><h2><?= $lang==='bg'?'Следващата стъпка е лична.':'Your next step is personal.' ?></h2><p><?= $lang==='bg'?'Разкажете ни за възрастта, ежедневието и поведението на вашето куче. Ще обсъдим подходяща посока за обучение.':'Tell us about your dog’s age, routine and behaviour. We can discuss the right training direction.' ?></p><a class="button button-acid" href="<?= k9e(k9_url('contact.php',null,'#contact-form')) ?>"><?= $lang==='bg'?'Обсъдете обучение':'Discuss training' ?></a></aside>
<div class="article-sources"><h2><?= $lang==='bg'?'Източници и допълнително четене':'Sources and further reading' ?></h2><p><?= $lang==='bg'?'Общите принципи следват препоръките на':'General principles follow guidance from' ?> <a href="https://avsab.org/resources/position-statements/" target="_blank" rel="noopener">American Veterinary Society of Animal Behavior</a> <?= $lang==='bg'?'за обучение с награди и безопасна социализация. Това е образователен материал, а не индивидуална оценка. При болка, внезапна промяна или риск от ухапване потърсете ветеринарен лекар и квалифициран специалист.':'on reward-based training and safe socialisation. This educational material is not an individual assessment. Seek a veterinarian and qualified professional for pain, sudden changes or bite risk.' ?></p></div>
</div></div></section></article></main>
<?php require __DIR__ . '/footer.php'; ?>
