<?php if (empty($ebookSectionRendered)): $ebookSectionRendered = true; ?>
<section class="ebook-section k9-textured" id="ebooks" aria-labelledby="ebook-title"><div class="site-container">
 <div class="editorial-section-heading"><div><p class="eyebrow">K9 / <?= $lang==='bg'?'БИБЛИОТЕКА':'THE LIBRARY' ?></p><h2 id="ebook-title"><?= $lang==='bg'?'Знание, което остава с вас.':'Guidance that stays with you.' ?></h2></div><p><?= $lang==='bg'?'Прочетете. Упражнете. Върнете се към най-важното. Изберете ръководството за вашия следващ етап.':'Read. Practise. Return to what matters. Choose the guide for your next stage.' ?></p></div>
 <div class="ebook-grid"><?php foreach ($products['products'] as $index=>$product): $book=$product[$lang]; ?>
  <article class="ebook-card"><a class="ebook-cover" href="<?= k9e(k9_url('ebooks.php',null,'#book-'.$product['slug'])) ?>"><img src="/assets/images/editorial/<?= k9e($product['slug']) ?>-cover.webp" width="640" height="960" alt="<?= k9e($book['title']) ?>" loading="lazy" decoding="async"><span class="ebook-cover-type"><small>K9 ACADEMY / 0<?= $index+1 ?></small><strong><?= k9e($book['title']) ?></strong><em><?= k9e($book['subtitle']) ?></em></span></a>
  <div class="ebook-card-copy" id="book-<?= k9e($product['slug']) ?>"><p class="eyebrow">PDF / BG + EN</p><h3><?= k9e($book['title']) ?></h3><p><?= k9e($book['description']) ?></p><ul><?php foreach ($book['features'] as $feature): ?><li><?= k9e($feature) ?></li><?php endforeach; ?></ul><div class="ebook-buy"><strong><?= number_format($product['cents']/100,2,$lang==='bg'?',':'.','') ?> €</strong><?php if ($products['enabled']): ?><form action="<?= k9e($products['endpoint']) ?>" method="post"><input type="hidden" name="product" value="<?= k9e($product['slug']) ?>"><input type="hidden" name="language" value="<?= k9e($lang) ?>"><button class="button button-acid" type="submit"><?= $lang==='bg'?'Купи PDF':'Buy PDF' ?></button></form><?php else: ?><a class="button button-ink" href="<?= k9e(k9_url('contact.php',null,'#contact-form')) ?>"><?= $lang==='bg'?'Попитайте за изданието':'Ask about this guide' ?></a><?php endif; ?></div></div>
  </article><?php endforeach; ?></div>
 <p class="ebook-delivery"><?= $products['enabled'] ? ($lang==='bg'?'Еднократна покупка. След потвърдено плащане получавате защитен линк за изтегляне и имейл с двата езикови PDF файла.':'One-time purchase. After confirmed payment, receive a protected download link and an email with both language editions.') : ($lang==='bg'?'Подготвяме електронните издания. Онлайн покупките ще бъдат достъпни след проверка на изтеглянето и доставката по имейл.':'We are preparing these digital editions. Online purchases will open after download and email delivery are verified.') ?></p>
</div></section>
<?php endif; ?>
