<?php
$pageKey='ebooks';
$hideEbooks=true;
require __DIR__.'/site.php';
require __DIR__.'/head.php';
require __DIR__.'/header.php';
?>
<main id="main-content"><section class="editorial-hero k9-textured"><div class="site-container"><p class="eyebrow">K9 / DIGITAL GUIDES</p><h1><?= k9e($editorial['pages']['ebooks'][$lang]['title']) ?></h1><p class="editorial-lead"><?= k9e($editorial['pages']['ebooks'][$lang]['intro']) ?></p></div></section>
<?php require __DIR__.'/ebook-section.php'; ?>
<section class="editorial-reading k9-textured"><div class="site-container reading-copy"><h2><?= $lang==='bg'?'Какво получавате?':'What do you receive?' ?></h2><p><?= $lang==='bg'?'Всеки продукт е самостоятелно PDF ръководство с българска и английска версия. Изтеглените файлове остават при вас за лично ползване. Индивидуална консултация или тренировъчна сесия не е включена в цената.':'Each product is a standalone PDF guide with Bulgarian and English editions. Downloaded files remain yours for personal use. The price does not include an individual consultation or training session.' ?></p><p><?= $lang==='bg'?'За безопасно начало вижте':'For a safe start, explore' ?> <a href="<?= k9e(k9_url('puppy.php')) ?>"><?= $lang==='bg'?'обучението на кученце':'puppy training' ?></a>. <?= $lang==='bg'?'Преди да вземете куче, прочетете за':'Before welcoming a dog, read about' ?> <a href="<?= k9e(k9_url('breeds.php')) ?>"><?= $lang==='bg'?'избора на порода':'choosing a breed' ?></a>.</p><h2><?= $lang==='bg'?'Покупка и помощ':'Purchase and support' ?></h2><p><?= $lang==='bg'?'Плащането се обработва от Stripe. Не събираме данни за банковата ви карта на този сайт. При проблем с изтеглянето пишете на mail.k9shop@gmail.com, като посочите номера на поръчката, без да изпращате данни за карта.':'Stripe processes payment. This site does not collect your card details. For download support, email mail.k9shop@gmail.com with your order reference and never send card information.' ?> <a href="<?= k9e(k9_url('terms.php')) ?>"><?= k9e(k9t('terms')) ?></a> · <a href="<?= k9e(k9_url('privacy.php')) ?>"><?= k9e(k9t('privacy')) ?></a>.</p></div></section><?php require __DIR__ . '/callback-section.php'; ?></main>
<?php require __DIR__.'/footer.php'; ?>
